### ISSUE TITLE
linux wheels failing

### ISSUE THREAD

**Issue by jreback** [MacPython/pandas-wheels#22]
failed: https://travis-ci.org/MacPython/pandas-wheels/builds/316711683

last working: https://travis-ci.org/MacPython/pandas-wheels/builds/314535880

@matthew-brett any idea here? these started linux builds failing I *think* when travis changed there builds (to new container) on dec 12, maybe we need to use older container?

**Comment by matthew-brett** [comment]
There seems to be something wrong with the new container.  Several builds are now failing with no error message - example : https://travis-ci.org/MacPython/h5py-wheels/jobs/318022378 - also happening with matplotlib.

I fixed some builds by adding:

```
unset -f pushd
unset -f popd
```

https://github.com/matthew-brett/multibuild/commit/7fe5a7a1cdde6d6b7354b47fd0ead2e7e9def0a4

See travis-ci/travis-ci#8703 (comment)

**Comment by matthew-brett** [comment]
Might be worth backing off to the previous container, so see whether that helps?

```
sudo: required
dist: trusty
group: deprecated-2017Q4
```

https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

**Comment by matthew-brett** [comment]
Just FYI - h5py builds on the exact same code have different matrix elements failing.

These two have the exact same code - just an empty commit difference between them - but different failures:

* https://travis-ci.org/MacPython/h5py-wheels/builds/318066503
* https://travis-ci.org/MacPython/h5py-wheels/builds/318088833

**Comment by jreback** [comment]
@matthew-brett I updated multibuild to use the devel branch, this seemed to fix one of the failures (the 3.5 linux build), but others still the same: https://travis-ci.org/MacPython/pandas-wheels/builds/321933462

any ideas?

**Comment by matthew-brett** [comment]
Oh dear - yes - I think you need : https://github.com/MacPython/h5py-wheels/commit/e8058ae720ef1fa1f8c45b912d311d11e6cd6783

**Comment by matthew-brett** [comment]
Cross-ref: https://github.com/travis-ci/travis-ci/issues/8920

**Comment by jreback** [comment]
trying!

**Comment by jreback** [comment]
looks like it is working

https://travis-ci.org/MacPython/pandas-wheels/builds/322510632

thanks!
